name: Website CI

on: 
  push:
    branches: [ main ] 

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Check Node and NPM Versions
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Insert Environment Variables
      run:
        cp /home/tony/backend.env ./backend/.env
    - name: Install Backend
      run:
        cd backend;
        npm i;
        cd ../;
    - name: Install Frontend
      run: 
        cd frontend;
        npm i;
        cd ../;
    - name: Build Frontend
      run: 
        cd frontend;
        npm run build;
        cd ../;
    - name: Restart PM2 Backend Process
      run:
        pm2 restart 0;
        pm2 save;
    - name: Restart Nginx Backend Process
      run:
        sudo service nginx restart;